logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never

spring:
  application:
    name: buddi-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  profiles:
    default: dev
  session:
    timeout: 7d
